theme: jekyll-theme-slate
name: Tamir Dresher, IBlogger
markdown: kramdown
permalink: /blog/:year/:month/:day/:title
title: IBlogger
description: Tamir Dresher | Blog
github: tamirdresher
linkedin: tamirdresher